amcl:
 min_particles: 500
 max_particles: 2000
 laser_max_range: 10.0
 laser_model_type: "likelihood_field"
 update_min_d: 0.2
 update_min_a: 3.0

 laser_max_beams: 150
 laser_z_hit: 0.5
 laser_z_rand: 0.8

 laser_sigma_hit: 0.2
 laser_z_max: 0.09
 laser_lambda_short: 0.1
 laser_likelihood_max_dist: 3.0
 resample_interval: 1
 transform_tolerance: 0.5

 recovery_alpha_slow: 0.001
 recover_alpha_fast: 0.1
